package com.example.smarthomedemo2.ui.theme

import androidx.compose.ui.graphics.Color

// Light Colors
val primaryLight = Color(0xFF006782)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFBBE9FF)
val onPrimaryContainerLight = Color(0xFF001F29)
val secondaryLight = Color(0xFF904D00)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFFFDCC0)
val onSecondaryContainerLight = Color(0xFF2E1500)
val tertiaryLight = Color(0xFF4C662B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCDEDA3)
val onTertiaryContainerLight = Color(0xFF102000)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFF7FBFF)
val onBackgroundLight = Color(0xFF181C1F)
val surfaceLight = Color(0xFFF7FBFF)
val onSurfaceLight = Color(0xFF181C1F)
val surfaceVariantLight = Color(0xFFDCE4E9)
val onSurfaceVariantLight = Color(0xFF40484C)
val outlineLight = Color(0xFF70787D)
val outlineVariantLight = Color(0xFFC0C8CD)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D3134)
val inverseOnSurfaceLight = Color(0xFFEEF1F5)
val inversePrimaryLight = Color(0xFF5ED4FE)
val surfaceDimLight = Color(0xFFD8DBDE)
val surfaceBrightLight = Color(0xFFF7FBFF)
val containerLowestLight = Color(0xFFFFFFFF)
val containerLowLight = Color(0xFFF1F4F8)
val containerLight = Color(0xFFEBFEFD)
val containerHighLight = Color(0xFFE5E8EC)
val containerHighestLight = Color(0xFFDFE2E6)

// Dark Colors
val primaryDark = Color(0xFF5ED4FE)
val onPrimaryDark = Color(0xFF003545)
val primaryContainerDark = Color(0xFF004D62)
val onPrimaryContainerDark = Color(0xFFBBE9FF)
val secondaryDark = Color(0xFFFFB77C)
val onSecondaryDark = Color(0xFF4D2700)
val secondaryContainerDark = Color(0xFF6D3900)
val onSecondaryContainerDark = Color(0xFFFFDCC0)
val tertiaryDark = Color(0xFFB1D18A)
val onTertiaryDark = Color(0xFF1F3701)
val tertiaryContainerDark = Color(0xFF354E16)
val onTertiaryContainerDark = Color(0xFFCDEDA3)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101417)
val onBackgroundDark = Color(0xFFDFE2E6)
val surfaceDark = Color(0xFF101417)
val onSurfaceDark = Color(0xFFDFE2E6)
val surfaceVariantDark = Color(0xFF40484C)
val onSurfaceVariantDark = Color(0xFFC0C8CD)
val outlineDark = Color(0xFF8A9297)
val outlineVariantDark = Color(0xFF40484C)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFDFE2E6)
val inverseOnSurfaceDark = Color(0xFF2D3134)
val inversePrimaryDark = Color(0xFF006782)
val surfaceDimDark = Color(0xFF101417)
val surfaceBrightDark = Color(0xFF363A3D)
val containerLowestDark = Color(0xFF0B0F11)
val containerLowDark = Color(0xFF181C1F)
val containerDark = Color(0xFF1C2023)
val containerHighDark = Color(0xFF272A2E)
val containerHighestDark = Color(0xFF323539)
